export_device:
  fields:
    device_id:
      required: true
      selector:
        device: {}
    filename:
      required: false
      example: "nibe_heat_pump.xlsx"
      selector:
        text: {}
    include_disabled:
      required: true
      default: true
      selector:
        boolean: {}
    include_attributes:
      required: true
      default: true
      selector:
        boolean: {}
